import { useEffect, useRef, useState } from "react";
// The wasm module is generated by `npm run build:wasm` into src/wasm/ (gitignored).
// `init` is the async initializer wasm-pack's `--target web` output exports; it
// fetches and instantiates the .wasm before any exported class can be used.
import init, { Simulation } from "../wasm/demo-bouncing/demo-bouncing.js";

// Instantiate the wasm module once and share the promise across every instance
// of this island on the page.
let wasmReady: Promise<unknown> | null = null;
function ensureWasm() {
  if (!wasmReady) wasmReady = init();
  return wasmReady;
}

interface Props {
  count?: number;
  height?: number;
}

/**
 * A bouncing-balls physics demo. The simulation runs in Rust/WebAssembly; this
 * component owns the canvas and the animation loop, reading a flat position
 * buffer from wasm each frame and drawing it.
 */
export default function BouncingBalls({ count = 60, height = 360 }: Props) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    let disposed = false;
    let raf = 0;
    let sim: Simulation | null = null;

    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    // Size the backing store to the CSS box × devicePixelRatio for crisp lines,
    // and keep the simulation's world coordinates in CSS pixels.
    let cssWidth = canvas.clientWidth || 640;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);

    function applySize() {
      cssWidth = canvas!.clientWidth || 640;
      canvas!.width = Math.round(cssWidth * dpr);
      canvas!.height = Math.round(height * dpr);
      ctx!.setTransform(dpr, 0, 0, dpr, 0, 0);
    }

    const ro = new ResizeObserver(() => {
      applySize();
      sim?.resize(cssWidth, height);
    });

    let last = 0;
    function frame(now: number) {
      if (disposed || !sim) return;
      const dt = last ? (now - last) / 1000 : 0;
      last = now;

      sim.tick(dt);
      const pos = sim.positions();

      ctx!.clearRect(0, 0, cssWidth, height);
      const accent =
        getComputedStyle(canvas!).getPropertyValue("--demo-accent") ||
        "#4f7cff";
      ctx!.fillStyle = accent.trim() || "#4f7cff";
      for (let i = 0; i < pos.length; i += 3) {
        const x = pos[i];
        const y = pos[i + 1];
        const r = pos[i + 2];
        ctx!.beginPath();
        ctx!.arc(x, y, r, 0, Math.PI * 2);
        ctx!.fill();
      }
      raf = requestAnimationFrame(frame);
    }

    ensureWasm().then(() => {
      if (disposed) return;
      applySize();
      // A fixed seed keeps the initial layout stable across reloads.
      sim = new Simulation(count, cssWidth, height, 0x9e3779b9);
      ro.observe(canvas);
      setReady(true);
      raf = requestAnimationFrame(frame);
    });

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      ro.disconnect();
      sim?.free();
    };
  }, [count, height]);

  return (
    <figure className="demo">
      <canvas
        ref={canvasRef}
        style={{ width: "100%", height: `${height}px`, display: "block" }}
        aria-label="Bouncing balls physics simulation running in WebAssembly"
      />
      {!ready && <p className="demo-loading">Loading simulation…</p>}
      <figcaption>
        Physics stepped in Rust → WebAssembly; drawn on a 2D canvas.
      </figcaption>
    </figure>
  );
}
